/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomerForm: typeof import('./src/components/CustomerForm.vue')['default']
    EmployeeItem: typeof import('./src/components/EmployeeItem.vue')['default']
    FullTimeSlot: typeof import('./src/components/FullTimeSlot.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceItem: typeof import('./src/components/ServiceItem.vue')['default']
    VueImminentComponent: typeof import('./src/components/VueImminentComponent.vue')['default']
  }
}
